//
//  StartScreenView.swift
//  MeruPush
//
//  Created by Mac on 20.08.2020.
//  Copyright (c) 2020 Lammax. All rights reserved.
//
//  This file was generated by the MVI Xcode Templates so
//  you can apply MVI architecture to your iOS and Mac projects
//


import SwiftUI

struct StartScreenView: View {
    
    @EnvironmentObject var settings: CommonSettings
    @Environment(\.colorScheme) var colorScheme
    
    @ObservedObject var intent = StartScreenIntent.sharedInstance
    
    var body: some View {
        ZStack {
            Button(action: {
                self.intent.registerDevice?()
            }) {
                Text("Register device")
                    .foregroundColor(.white)
                    .background(Color.green)
            }
        }
        .onAppear {
            self.intent.setup(settings: self.settings)
        }
    }
    
}

struct StartScreenView_Previews: PreviewProvider {
    static var previews: some View {
        StartScreenView()
    }
}
