//
//  StartScreenModel.swift
//  MeruPush
//
//  Created by Mac on 20.08.2020.
//  Copyright (c) 2020 Lammax. All rights reserved.
//
//  This file was generated by the MVI Xcode Templates so
//  you can apply MVI architecture to your iOS and Mac projects
//

import Foundation

enum StartScreen {
    
    // MARK: Use cases
    
    struct Info {
        let info: Any?
    }
    
}
