//
//  MainScreenView.swift
//  MeruPush
//
//  Created by Mac on 20.08.2020.
//  Copyright (c) 2020 Lammax. All rights reserved.
//
//  This file was generated by the MVI Xcode Templates so
//  you can apply MVI architecture to your iOS and Mac projects
//


import SwiftUI

struct MainScreenView: View {
    
    @EnvironmentObject var settings: CommonSettings
    @Environment(\.colorScheme) var colorScheme
    
    @ObservedObject var intent = MainScreenIntent()
    
    var body: some View {
        containerView()
        .onAppear {
            self.intent.setup(settings: self.settings)
        }
    }
    
    func containerView() -> AnyView {
        switch settings.currentScreen {
            case .start:
                return AnyView(StartScreenView().environmentObject(settings))
            case .screen1:
                return AnyView(Screen1View().environmentObject(settings))
            case .screen2:
                return AnyView(Screen2View().environmentObject(settings))
        }
    }
    
}

struct MainScreenView_Previews: PreviewProvider {
    static var previews: some View {
        MainScreenView()
    }
}
