//
//  Screen2View.swift
//  MeruPush
//
//  Created by Mac on 20.08.2020.
//  Copyright (c) 2020 Lammax. All rights reserved.
//
//  This file was generated by the MVI Xcode Templates so
//  you can apply MVI architecture to your iOS and Mac projects
//


import SwiftUI

struct Screen2View: View {
    
    @EnvironmentObject var settings: CommonSettings
    @Environment(\.colorScheme) var colorScheme
    
    @ObservedObject var intent = Screen2Intent()
    
    var body: some View {
        ZStack {
            Text("Screen2")
        }
        .onAppear {
            self.intent.setup(settings: self.settings)
        }
    }
    
}

struct Screen2View_Previews: PreviewProvider {
    static var previews: some View {
        Screen2View()
    }
}
