//
//  Screen1View.swift
//  MeruPush
//
//  Created by Mac on 20.08.2020.
//  Copyright (c) 2020 Lammax. All rights reserved.
//
//  This file was generated by the MVI Xcode Templates so
//  you can apply MVI architecture to your iOS and Mac projects
//


import SwiftUI

struct Screen1View: View {
    
    @EnvironmentObject var settings: CommonSettings
    @Environment(\.colorScheme) var colorScheme
    
    @ObservedObject var intent = Screen1Intent()
    
    var body: some View {
        VStack(alignment: .center, spacing: 20) {
            Text("Screen 1")
            Text(settings.bodyText)
                .lineLimit(nil)
                .multilineTextAlignment(.center)
                .frame(maxWidth: UIScreen.main.bounds.width - 100.0)
        }
        .onAppear {
            self.intent.setup(settings: self.settings)
        }
    }
    
}

struct Screen1View_Previews: PreviewProvider {
    static var previews: some View {
        Screen1View()
    }
}
